export const ALL_TOUR_REQUEST = "ALL_TOUR_REQUEST";
export const ALL_TOUR_SUCCESS = "ALL_TOUR_SUCCESS";
export const ALL_TOUR_FAIL = "ALL_TOUR_FAIL";

export const TOUR_DETAILS_REQUEST = "TOUR_DETAILS_REQUEST";
export const TOUR_DETAILS_SUCCESS = "TOUR_DETAILS_SUCCESS";
export const TOUR_DETAILS_FAIL = "TOUR_DETAILS_FAIL";


export const CLEAR_ERRORS= "CLEAR_ERRORS";